# SPDX-License-Identifier: GPL-2.0-only
PACKAGE_NAME="t2-sep-transport"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="t2_sep_transport"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
MAKE[0]="make -C src KDIR=/lib/modules/$kernelver/build module"
AUTOINSTALL="yes"
