# SPDX-License-Identifier: GPL-2.0-only
# Research candidate only. install.sh deliberately does not install this file.
[Service]
ExecStart=
ExecStart=/opt/t2-touchid/.venv/bin/python /opt/t2-touchid/src/t2-fprintd.py --enable-native-enrollment --enable-native-deletion
