#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
set -u
PATH=/usr/bin:/bin
export PATH
ulimit -c 0

TOOL=/usr/local/sbin/t2-aks-tool
STATE_FILE=/run/t2-touchid/keybag.env
CONFIG_FILE=/etc/t2-touchid.conf

# This hook is intentionally a no-op for other users or unavailable state.
[[ -r $CONFIG_FILE && -r $STATE_FILE && -x $TOOL ]] || exit 0
configured_user=$(sed -n 's/^T2_TOUCHID_USER=\([A-Za-z0-9_.-][A-Za-z0-9_.-]*\)$/\1/p' "$CONFIG_FILE")
[[ -n $configured_user && ${PAM_USER:-} == "$configured_user" ]] || exit 0

# The file is generated by t2-keybag-load and is root-only. Validate every
# value rather than sourcing it.
session=$(sed -n 's/^T2_KEYBAG_SESSION=\([0-9][0-9]*\)$/\1/p' "$STATE_FILE")
handle=$(sed -n 's/^T2_KEYBAG_HANDLE=\(-\{0,1\}[0-9][0-9]*\)$/\1/p' "$STATE_FILE")
special=$(sed -n 's/^T2_KEYBAG_SPECIAL=\(-\{0,1\}[0-9][0-9]*\)$/\1/p' "$STATE_FILE")
[[ -n $session && -n $handle && -n $special ]] || exit 0

# pam_exec expose_authtok supplies the password on stdin. Keep it out of
# argv, the environment, logs, and persistent storage.
IFS= read -r password || [[ -n ${password:-} ]] || exit 0
[[ -n $password ]] || exit 0

normal_ok=0
special_ok=0
printf '%s\n' "$password" | "$TOOL" unlock-keybag-stdin "$session" "$handle" >/dev/null 2>&1 && normal_ok=1
printf '%s\n' "$password" | "$TOOL" unlock-keybag-stdin "$session" "$special" >/dev/null 2>&1 && special_ok=1
unset password
if [[ $normal_ok == 1 && $special_ok == 1 ]]; then
  logger --priority authpriv.info --tag t2-pam-unlock 'keybags unlocked from PAM password authentication'
else
  logger --priority authpriv.warning --tag t2-pam-unlock 'keybag unlock attempt failed closed'
fi
exit 0
